### ISSUE TITLE
Bump nessus-agent to 10.1.4 or newer to resolve findings

### ISSUE THREAD

**Issue by pburkholder** [18F/cg-nessus-agent-boshrelease#44]
Bump nessus-agent to 10.1.4 or newer to resolve findings

See https://github.com/cloud-gov/cg-nessus-agent-boshrelease/pull/40 for a similar update.

**Comment by pburkholder** [comment]
Hey squad folks - is this something you can schedule in the next week?

**Comment by rbogle** [comment]
Make PR https://github.com/cloud-gov/cg-nessus-agent-boshrelease/pull/45

**Comment by markdboyd** [comment]
#45 was merged so this can be closed
